# Copyright Cisco
# SPDX-License-Identifier: Apache-2.0
from typing import Optional

class Generator:
    def __init__(self, protocol: int = 3, seed: Optional[int] = None) -> None: ...
    def generate(self) -> bytes: ...
    def generate_from_bytes(self, data: bytes) -> bytes: ...
    def set_opcode_range(self, min: int, max: int) -> None: ...
    def reset(self) -> None: ...
